### PR TITLE
[CI] Reusable CI

### PR DESCRIPTION
**Pull request by orensbruli**
Modified build.yaml to use reusable workflow.

Signed-off-by: Esteban Martinena <orensbruli@gmail.com>

### CODE REVIEW

**Comment by orensbruli** [comment]
The checks are really failing but probably not set to be needed to merge? 
This is the run of the same PR in my fork:
https://github.com/orensbruli/rmf_utils/actions/runs/3071565382

**Comment by orensbruli** [comment]
Not sure if it ever worked or if it's failing with the same error now as 3 months ago:
https://github.com/open-rmf/rmf_utils/actions/workflows/build.yaml

**Comment by mxgrey** [comment]
Looks like it's just style complaints:

```
  2: --- include/rmf_utils/clone_ptr.hpp
  2: +++ include/rmf_utils/clone_ptr.hpp.uncrustify
  2: @@ -42 +42 @@
  2: -clone_ptr<T> make_clone(Args&&... args);
  2: +clone_ptr<T> make_clone(Args&& ... args);
  2: @@ -197 +197 @@
  2: -clone_ptr<T> make_clone(Args&&... args)
  2: +clone_ptr<T> make_clone(Args&& ... args)
  2: 
  2: Code style divergence in file 'include/rmf_utils/impl_ptr.hpp':
  2: 
  2: --- include/rmf_utils/impl_ptr.hpp
  2: +++ include/rmf_utils/impl_ptr.hpp.uncrustify
  2: @@ -323 +323 @@
  2: -inline unique_impl_ptr<T> make_unique_impl(Args&&... args)
  2: +inline unique_impl_ptr<T> make_unique_impl(Args&& ... args)
  2: @@ -477 +477 @@
  2: -inline impl_ptr<T> make_impl(Args&&... args)
  2: +inline impl_ptr<T> make_impl(Args&& ... args)
  2: @@ -484 +484 @@
  2: -impl_ptr<U> make_derived_impl(Args&&... args)
  2: +impl_ptr<U> make_derived_impl(Args&& ... args)
```

**Comment by orensbruli** [comment]
> Looks like it's just style complaints:

Fixed those but it looks like for focal ones it's the same problem we found here: https://github.com/open-rmf/rmf/pull/202#issuecomment-1242169211

We could try to go with any of the two options suggested here and wait (https://github.com/open-rmf/rmf/pull/202#issuecomment-1242169211) or I could avoid the workflow to run in focal-based distros. What do you think?

**Review by marcoag — APPROVED** [review]

**Pull request merged**
